/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import controller.EquipamentoDAO;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import model.Equipamento;

/**
 *
 * @author Admin
 */
public class EditarEquipamento extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(EditarEquipamento.class.getName());

    /**
     * Creates new form CadastroEquipamento
     */
    public EditarEquipamento() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        nomeEquipamento = new javax.swing.JTextField();
        patrimonioEquipamento = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        Salvar = new javax.swing.JButton();
        Limpar = new javax.swing.JButton();
        Cancelar = new javax.swing.JButton();
        descriçaoEquipamento = new javax.swing.JTextField();
        quantidadeEquipamento = new javax.swing.JTextField();
        marcaEquipamento = new javax.swing.JTextField();
        estadoConservaçao = new javax.swing.JComboBox<>();
        salaEquipamento = new javax.swing.JTextField();
        botaoX = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("EDITAR");

        jLabel2.setText("Nome:");

        patrimonioEquipamento.addActionListener(this::patrimonioEquipamentoActionPerformed);

        jLabel3.setText("Patrimonio:");

        jLabel4.setText("Descrição:");

        jLabel5.setText("Quantidade:");

        jLabel6.setText("Marca:");

        jLabel7.setText("Sala:");

        jLabel8.setText("Estado de Conservação");

        Salvar.setText("Salvar");
        Salvar.addActionListener(this::SalvarActionPerformed);

        Limpar.setText("Limpar");
        Limpar.addActionListener(this::LimparActionPerformed);

        Cancelar.setText("Cancelar");

        quantidadeEquipamento.addActionListener(this::quantidadeEquipamentoActionPerformed);

        marcaEquipamento.addActionListener(this::marcaEquipamentoActionPerformed);

        estadoConservaçao.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ativo", "Inativo", "Parcialmente Ativo", " " }));
        estadoConservaçao.addActionListener(this::estadoConservaçaoActionPerformed);

        salaEquipamento.addActionListener(this::salaEquipamentoActionPerformed);

        botaoX.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        botaoX.setText("X");
        botaoX.addActionListener(this::botaoXActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(18, 18, 18)
                        .addComponent(quantidadeEquipamento, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(nomeEquipamento, javax.swing.GroupLayout.DEFAULT_SIZE, 369, Short.MAX_VALUE)
                            .addComponent(patrimonioEquipamento, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(descriçaoEquipamento, javax.swing.GroupLayout.PREFERRED_SIZE, 357, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(estadoConservaçao, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(110, 110, 110)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(salaEquipamento, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(marcaEquipamento, javax.swing.GroupLayout.DEFAULT_SIZE, 111, Short.MAX_VALUE)))
                .addGap(28, 28, 28))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addComponent(Salvar)
                .addGap(93, 93, 93)
                .addComponent(Limpar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Cancelar)
                .addGap(62, 62, 62))
            .addGroup(layout.createSequentialGroup()
                .addGap(237, 237, 237)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(botaoX))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1))
                    .addComponent(botaoX))
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(nomeEquipamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(patrimonioEquipamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(37, 37, 37)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(quantidadeEquipamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6)
                            .addComponent(marcaEquipamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(estadoConservaçao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7)
                            .addComponent(salaEquipamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(44, 44, 44)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Salvar)
                            .addComponent(Limpar)
                            .addComponent(Cancelar)))
                    .addComponent(descriçaoEquipamento, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(36, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void LimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LimparActionPerformed
        nomeEquipamento.setText(" ");
        patrimonioEquipamento.setText("");
        descriçaoEquipamento.setText(" ");
        quantidadeEquipamento.setText("");
        marcaEquipamento.setText(" ");
        estadoConservaçao.setSelectedItem("");
        salaEquipamento.setText(" ");
    }//GEN-LAST:event_LimparActionPerformed

    private void patrimonioEquipamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_patrimonioEquipamentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_patrimonioEquipamentoActionPerformed

    private void quantidadeEquipamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quantidadeEquipamentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_quantidadeEquipamentoActionPerformed

    private void estadoConservaçaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_estadoConservaçaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_estadoConservaçaoActionPerformed

    private void marcaEquipamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_marcaEquipamentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_marcaEquipamentoActionPerformed

    private void salaEquipamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salaEquipamentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_salaEquipamentoActionPerformed

    private void SalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalvarActionPerformed
        Equipamento equipamento = new Equipamento();
        EquipamentoDAO equiDAO = new EquipamentoDAO();
        

        String nome, descricao, marca, estadoConservacao, patrimonio;
        
        int quantidade, sala;

        nome = nomeEquipamento.getText();
        equipamento.setNome(nome);
        
        patrimonio = patrimonioEquipamento.getText();
        equipamento.setPatrimonio(patrimonio);

        descricao = descriçaoEquipamento.getText();
        equipamento.setDescricao(descricao);

        quantidade = Integer.parseInt(quantidadeEquipamento.getText());
        equipamento.setQuantidade(quantidade);
        
        marca = marcaEquipamento.getText();
        equipamento.setMarca(marca);
        
        estadoConservacao = (String)estadoConservaçao.getSelectedItem();
        equipamento.setEstadoConservacao(estadoConservacao);
        
        sala = Integer.parseInt(salaEquipamento.getText());
        equipamento.setSala(sala);
       

        try {
            equiDAO.alterar(equipamento);
            JOptionPane.showMessageDialog(null,"Editado com Sucesso");
            
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null,"Não foi editado" + ex);
        }
    }//GEN-LAST:event_SalvarActionPerformed

    private void botaoXActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoXActionPerformed
        dispose();
    }//GEN-LAST:event_botaoXActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new EditarEquipamento().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Cancelar;
    private javax.swing.JButton Limpar;
    private javax.swing.JButton Salvar;
    private javax.swing.JButton botaoX;
    private javax.swing.JTextField descriçaoEquipamento;
    private javax.swing.JComboBox<String> estadoConservaçao;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField marcaEquipamento;
    private javax.swing.JTextField nomeEquipamento;
    private javax.swing.JTextField patrimonioEquipamento;
    private javax.swing.JTextField quantidadeEquipamento;
    private javax.swing.JTextField salaEquipamento;
    // End of variables declaration//GEN-END:variables
}
